# Clock signal
set_property PACKAGE_PIN E3 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# Reset pin (active high, mapped to BTNC)
set_property PACKAGE_PIN N17 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]

# Button inputs (mapped to Nexys A7 buttons)
set_property PACKAGE_PIN M18 [get_ports btnU]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN P18 [get_ports btnD]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnD]
set_property PACKAGE_PIN P17 [get_ports btnL]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnL]
set_property PACKAGE_PIN M17 [get_ports btnR]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnR]
# Paint toggle button (using SW15 since all dedicated buttons are in use)
# Paint toggle button
set_property PACKAGE_PIN T8 [get_ports paint_btn]
    set_property IOSTANDARD LVCMOS33 [get_ports paint_btn]
# Color select input (5-bit bus, using switch pins)
set_property PACKAGE_PIN J15 [get_ports {color_select[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {color_select[0]}]
set_property PACKAGE_PIN L16 [get_ports {color_select[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {color_select[1]}]
set_property PACKAGE_PIN M13 [get_ports {color_select[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {color_select[2]}]
set_property PACKAGE_PIN R15 [get_ports {color_select[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {color_select[3]}]
set_property PACKAGE_PIN R17 [get_ports {color_select[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {color_select[4]}]

# VGA output signals (mapped to Nexys A7 VGA connector)
set_property PACKAGE_PIN B11 [get_ports hsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN B12 [get_ports vsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN A3 [get_ports {vga_red[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN B4 [get_ports {vga_red[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_red[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN A4 [get_ports {vga_red[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN C6 [get_ports {vga_green[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property PACKAGE_PIN A5 [get_ports {vga_green[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN B6 [get_ports {vga_green[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN A6 [get_ports {vga_green[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN B7 [get_ports {vga_blue[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property PACKAGE_PIN C7 [get_ports {vga_blue[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN D7 [get_ports {vga_blue[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_blue[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
